from __future__ import annotations

APP_VERSION = "2.0.0"
DB_FILENAME = "runtime_store.db"

ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_REGIONAL_MANAGER = "REGIONAL_MANAGER"
ROLE_ASSOCIATE_MANAGER = "ASSOCIATE_MANAGER"
ROLE_LOCAL_MANAGER = "LOCAL_MANAGER"
ROLE_CANDIDATE = "CANDIDATE"

ROLE_ORDER = (
    ROLE_SUPER_ADMIN,
    ROLE_REGIONAL_MANAGER,
    ROLE_ASSOCIATE_MANAGER,
    ROLE_LOCAL_MANAGER,
    ROLE_CANDIDATE,
)

MANAGER_ROLES = (
    ROLE_SUPER_ADMIN,
    ROLE_REGIONAL_MANAGER,
    ROLE_ASSOCIATE_MANAGER,
    ROLE_LOCAL_MANAGER,
)

DIRECT_CHILD_ROLES: dict[str, tuple[str, ...]] = {
    ROLE_SUPER_ADMIN: (ROLE_REGIONAL_MANAGER,),
    ROLE_REGIONAL_MANAGER: (ROLE_ASSOCIATE_MANAGER, ROLE_LOCAL_MANAGER),
    ROLE_ASSOCIATE_MANAGER: (ROLE_LOCAL_MANAGER,),
    ROLE_LOCAL_MANAGER: (ROLE_CANDIDATE,),
    ROLE_CANDIDATE: (),
}

MANAGEABLE_ROLES: dict[str, tuple[str, ...]] = {
    ROLE_SUPER_ADMIN: (
        ROLE_REGIONAL_MANAGER,
        ROLE_ASSOCIATE_MANAGER,
        ROLE_LOCAL_MANAGER,
        ROLE_CANDIDATE,
    ),
    ROLE_REGIONAL_MANAGER: (ROLE_ASSOCIATE_MANAGER, ROLE_LOCAL_MANAGER, ROLE_CANDIDATE),
    ROLE_ASSOCIATE_MANAGER: (ROLE_LOCAL_MANAGER, ROLE_CANDIDATE),
    ROLE_LOCAL_MANAGER: (ROLE_CANDIDATE,),
    ROLE_CANDIDATE: (),
}

RECORD_STATUS_OPEN = "Open"
RECORD_STATUS_CLONE = "Clone"
RECORD_STATUS_IN_PROGRESS = "In Progress"
RECORD_STATUS_FORFEITED = "Forfeited"

RECORD_STATUSES = (
    RECORD_STATUS_OPEN,
    RECORD_STATUS_CLONE,
    RECORD_STATUS_IN_PROGRESS,
    RECORD_STATUS_FORFEITED,
)

SOURCE_MODE_OFFLINE = "OFFLINE"
SOURCE_MODE_ONLINE = "ONLINE"
SOURCE_MODES = (SOURCE_MODE_OFFLINE, SOURCE_MODE_ONLINE)

PASSWORD_STATE_ACTIVE = "ACTIVE"
PASSWORD_STATE_RESET_REQUIRED = "RESET_REQUIRED"
PASSWORD_STATES = (PASSWORD_STATE_ACTIVE, PASSWORD_STATE_RESET_REQUIRED)

AUDIT_ACTION_LOGIN = "LOGIN"
AUDIT_ACTION_LOGIN_FAILED = "LOGIN_FAILED"
AUDIT_ACTION_USER_CREATED = "USER_CREATED"
AUDIT_ACTION_USER_UPDATED = "USER_UPDATED"
AUDIT_ACTION_PASSWORD_RESET = "PASSWORD_RESET"
AUDIT_ACTION_RECORD_CREATED = "RECORD_CREATED"
AUDIT_ACTION_RECORD_UPDATED = "RECORD_UPDATED"
AUDIT_ACTION_RECORD_RESTORED = "RECORD_RESTORED"
AUDIT_ACTION_PERMISSION_DENIED = "PERMISSION_DENIED"
AUDIT_ACTION_IMPORT_PREVIEW = "IMPORT_PREVIEW"
AUDIT_ACTION_IMPORT_COMMIT = "IMPORT_COMMIT"
AUDIT_ACTION_SOURCE_CONFIG_UPDATED = "SOURCE_CONFIG_UPDATED"
AUDIT_ACTION_RECOVERY = "RECOVERY"

DEFAULT_SOURCE_CONFIG = {
    "source_mode": SOURCE_MODE_OFFLINE,
    "local_path": "",
    "remote_url": "",
    "is_active": 1,
    "last_sync_at": "",
    "last_sync_status": "Never synced",
    "last_checksum": "",
    "last_error": "",
}

LEGACY_RECORD_HEADERS = [
    "record_id",
    "title",
    "category",
    "name",
    "phone_number",
    "status",
    "short_note",
    "created_at",
    "updated_at",
]

IMPORT_REQUIRED_COLUMNS = {
    "login_id",
    "role",
    "display_name",
}

IMPORT_OPTIONAL_COLUMNS = {
    "referral_code",
    "parent_login_id",
    "password",
    "deployed_location",
    "phone",
    "active_flag",
}
